name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-scanner:
    name: Run SonarQube Scanner
    runs-on: ubuntu-latest  # You can use 'windows-latest' or 'macos-latest' as well

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache SonarQube scanner dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Install SonarQube Scanner
      run: |
        curl -sSLo sonarqube-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        mv sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner

    - name: Set SONAR_TOKEN
      run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV  # Securely pass the token via GitHub secrets

    - name: Run SonarQube analysis
      run: |
        /usr/local/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.sources=src \
          -Dsonar.host.url=http://your-sonarqube-url:9000 \
          -Dsonar.login=$SONAR_TOKEN
